# Example configuration file for ownarr
# This file demonstrates all available configuration options

# Port to listen on (default: 8080)
port: 8080

# Log level (default: "info")
# Valid values: "debug", "info", "warn", "error"
logLevel: "info"

# Polling interval for checking folder changes (default: "30s")
# Format: number with unit (e.g., "10s", "5m", "1h")
pollInterval: "30s"

# Timezone for logging and scheduling (default: "UTC")
# Uses standard timezone names (e.g., "America/New_York", "Europe/London")
timezone: "UTC"

# List of folders to monitor
# New format (recommended):
# You can use just 'mode' for all files/directories, or specify 'fileMode' and 'dirMode' separately
folders:
  - path: "/data/media"
    uid: 1000
    gid: 1000
    mode: 755        # Default mode for the folder, and fallback for files/dirs if not specified
    fileMode: 644    # Optional: specific permissions for files (uses 'mode' if not specified)
    dirMode: 755     # Optional: specific permissions for subdirectories (uses 'mode' if not specified)
  - path: "/data/downloads"
    uid: 1000
    gid: 1000
    mode: 755        # If fileMode and dirMode are omitted, everything uses this mode
    # fileMode: 644    # Uncomment to set specific file permissions
    # dirMode: 755     # Uncomment to set specific directory permissions

# Legacy format (removed):
# The old format "/path:uid:gid:mode" is no longer supported.
