# Application configuration example

# Logging level: debug, info, warning, error, critical
log_level: "info"

poll_interval: 30  # Interval in seconds to poll for changes

# Directories to watch for changes
watch_dirs:
  - path: "/data/media"
    recursive: true           # Watch subdirectories
    exclude:                  # Patterns to exclude from watching
      - "temp"
      - "*.tmp"
      - "*.bak"               # Exclude backup files
      - ".DS_Store"           # Exclude macOS metadata files
    include:                  # (Optional) Patterns to explicitly include
      - "*.mp4"
      - "*.mkv"
      - "*.avi"
    file_mode: "0644"         # Default file permissions
    dir_mode: "0755"          # Default directory permissions
